[IMP] Forbid other users from deleting messages, add a delete function.
sunflowerit/social pull request #2
Opened 2018-04-09 17:05 UTC by daramousk

2018-04-10 18:02 UTC, thomaspaulb commented
@hbrunn Could you review this first?

2018-04-10 19:30 UTC, hbrunn requested changes

2018-04-10 19:30 UTC, hbrunn commented on mail_edit/models/mail_message.py
> +                    if rec.create_uid.id != self.env.uid and \
I still disagree with this, now with an argument: An admin (someone from group_system, but not root) goes to settings/technical regularly to clean up some mail messages. Don't ask why that's not automated. Maybe it's only fishing out the bosses last late night mail, doesn't matter. But they won't be able to do that any more after installing this module, and there's no way around it like changing access rules or the like, which would be somehow acceptable.

I think that's highly unexpected, and software shouldn't surprise experienced users who have read the manual. So no, please do that on the client side.

2018-04-10 19:30 UTC, hbrunn commented on mail_edit/static/src/js/mail_edit.js
> +            mail_message_model.call('unlink', [this.id]).then(
it seems to me checking https://github.com/OCA/OCB/blob/8.0/addons/mail/static/src/js/mail.js#L171 should be enough to do the right thing here already?

2018-04-10 19:30 UTC, hbrunn commented on mail_edit/static/src/js/mail_edit.js
> +            mail_message_model.call('unlink', [this.id]).then(
why don't you call https://github.com/OCA/OCB/blob/8.0/addons/mail/static/src/js/mail.js#L1036 anyways? you get a confirmation dialog and if I read the code correctly fancy fadeout for free, then your also don't need the awkward parent assumption (what if the chatter is somewhere else on the form?)

2018-04-10 19:30 UTC, hbrunn commented on mail_edit/static/src/xml/mail_edit.xml
> +            <span class="oe_delete">
how about ``t-if="widget.is_author``? Or even ``t-att-disabled="widget.is_author None or 'disabled'"`` (from the top off my head, untested). Then there's no need to check for author above

2018-04-13 13:04 UTC, daramousk commented
@hbrunn Done

2018-04-16 05:53 UTC, hbrunn approved these changes

2018-04-22 08:45 UTC, daramousk commented
@thomaspaulb Anything else you need me to do on this?

2018-04-23 12:02 UTC, thomaspaulb commented
@daramousk Nope, looks good, tested and works well also.

2018-04-23 12:02 UTC, merged